name: Release on tag

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository with history to access branch information
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history to find branch

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Get the version tag from the Git ref
      - name: Extract tag version
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Get the branch associated with the tag
      - name: Get branch from tag
        id: get_branch
        run: |
          BRANCH=$(git branch -r --contains $GITHUB_SHA | grep -v '\->' | sed -n 1p | sed 's/.*origin\///')
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      # Update the 'version' file with the new tag
      - name: Update version file
        run: echo "${{ env.TAG_NAME }}" > version

      # Commit the updated version file
      - name: Commit updated version file
        run: |
          git checkout ${{ env.BRANCH_NAME }}  # Checkout the branch associated with the tag
          git add version
          git commit -m "Update version to ${{ env.TAG_NAME }}"
          git push origin ${{ env.BRANCH_NAME }}

      # Create a release
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
